[package]
name = "totems"
version = "0.1.1"
authors = ["ObliqueMotion <aeketn@gmail.com>"]
edition = "2018"
description = "A collection of assertions for unit tests."
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/ObliqueMotion/totems-rs"

[dependencies]
