[package]
name = "totems"
version = "0.1.6"
authors = ["ObliqueMotion <aeketn@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "A collection of assertions for unit testing."
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/ObliqueMotion/totems-rs"

[dependencies]
